"""
Copyright start
MIT License
Copyright (c) 2024 Fortinet Inc
Copyright end
"""

#FSR Autogenerated Content. DO NOT DELETE
from .operations import make_api_call
 
supported_operations = {'make_api_call': make_api_call, }